name: ethiopian_historic_places_ar
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  model_viewer_plus: ^1.2.0
  flutter_tts: ^3.3.3
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  image: ^3.1.3
  image_picker: ^0.8.5
  new_im_animations: ^0.1.1
  flutter_secure_storage: ^5.0.2
  audioplayers: ^0.20.1
  font_awesome_flutter: ^10.1.0
  flutter_riverpod: ^1.0.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/img/
    - assets/ar/
    - assets/models/
    - assets/audio/

  fonts:
    - family: Macondo
      fonts:
        - asset: assets/fonts/Macondo-Regular.ttf

  plugin:
    platforms:
      android:
        package: com.tfliteflutter.tflite_flutter_helper
        pluginClass: TfliteFlutterHelperPlugin
      ios:
        pluginClass: TfliteFlutterHelperPlugin
      linux:
        pluginClass: TfliteFlutterHelperPlugin
      macos:
        pluginClass: TfliteFlutterHelperPlugin
      windows:
        pluginClass: TfliteFlutterHelperPlugin
